version: "3.8"
services:
  catalog_api:
    image: docker.io/library/catalog-api:v1
    container_name: catalog_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    environment:
      - ConnectionStrings__DefaultConnection=${POSTGRES_CONNECTION_STRING}
      - ASPNETCORE_URLS=http://+:80
    networks:
      - netLecture
    depends_on:
      - postgres_db
    env_file:
      - .env

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5433:5432"
    networks:
      - netLecture
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "15432:80"
    depends_on:
      - postgres_db

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - netLecture
        
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - netLecture
        
        
volumes:
  mongo_data:
    driver: local
  postgres_data:
    driver: local

networks:
  netLecture:
    driver: bridge
